### ISSUE TITLE
Any way to save the output markdown into folder ?

### ISSUE THREAD

**Issue by drmetro09** [xiaoyao9184/docker-marker#1]
any way to save the output into folder ?

**Comment by xiaoyao9184** [comment]
You should directly reference the [marker](https://github.com/VikParuchuri/marker) project 

or use this project to run as a [gradio](https://huggingface.co/spaces/xiaoyao9184/marker) service and use `gradio_client`.

There will be an API interface at the bottom of each gradio project.

**Comment by drmetro09** [comment]
> You should directly reference the [marker](https://github.com/VikParuchuri/marker) project
> 
> or use this project to run as a [gradio](https://huggingface.co/spaces/xiaoyao9184/marker) service and use `gradio_client`.
> 
> There will be an API interface at the bottom of each gradio project.

Is it possible to mount the output folder ?

**Comment by drmetro09** [comment]
I just want it to save the markdown file to a folder , how can i do it ?

**Comment by xiaoyao9184** [comment]
you need to call [convert_single.py](https://github.com/VikParuchuri/marker/tree/master?tab=readme-ov-file#convert-a-single-file) or [convert.py](https://github.com/VikParuchuri/marker/tree/master?tab=readme-ov-file#convert-multiple-files)

**Comment by drmetro09** [comment]
> you need to call [convert_single.py](https://github.com/VikParuchuri/marker/tree/master?tab=readme-ov-file#convert-a-single-file) or [convert.py](https://github.com/VikParuchuri/marker/tree/master?tab=readme-ov-file#convert-multiple-files)

How to do that from gradio ui ? Can you please explain?

**Comment by xiaoyao9184** [comment]
You can run any commands provided by Marker. However, unless it is a one-time task, it is not recommended to use command scripts for execution, as the model will be reloaded each time. Below is an example of using an offline model to process batch PDF file inputs and output them as MD files.

```yml
services:
  marker_pdf_convert:
    image: xiaoyao9184/marker:1.0.0
    container_name: marker_pdf_convert
    command: marker /pdf_in --output_dir /md_out
    environment:
      - TORCH_DEVICE=cuda
      - HF_HUB_OFFLINE=true
      - DETECTOR_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_det3/snapshots/467ee9ec33e6e6c5f73e57dbc1415b14032f5b95
      - LAYOUT_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--datalab-to--surya_layout0/snapshots/421ac206a400227ea714d47a405e53ce74374957
      - RECOGNITION_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_rec2/snapshots/6611509b2c3a32c141703ce19adc899d9d0abf41
      - TABLE_REC_MODEL_CHECKPOINT=/root/.cache/huggingface/hub/models--vikp--surya_tablerec/snapshots/8bca165f81e9cee5fb382413eb23175079917d14
      - TEXIFY_MODEL_NAME=/root/.cache/huggingface/hub/models--vikp--texify/snapshots/ce49c1fe10842e78b8be61f9e762b85ac952807d
    volumes:
      - ./../../cache:/root/.cache
      - ./../../pdf_in:/pdf_in
      - ./../../md_out:/md_out
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

```
